# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:macos)

platform :macOS do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    sync_code_signing(
      type: "appstore",
      app_identifier: 'com.ampersands.gridy',
      readonly: true
    )
    increment_build_number(xcodeproj: "gridy.xcodeproj")
    build_app(scheme: "gridy")
    upload_to_testflight
  end
end
